[project]
authors = ["silask <silas.kieser@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "whisper_streaming_web"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
librosa = ">=0.10.2.post1,<0.11"
fastapi = ">=0.115.6,<0.116"
ffmpeg-python = ">=0.2.0,<0.3"
mosestokenizer = "*"
uvicorn = "*" # for server
sentencepiece = ">=0.2.0,<0.3"





[pypi-dependencies]
soundfile = "*"
mlx-whisper = ">=0.4.1, <0.5"
torch = ">=2.5.1, <3"
wtpsplit = ">=2.1.2, <3"
tokenize-uk = ">=0.2.0, <0.3"
faster-whisper = ">=1.1.0, <2"
torchaudio = ">=2.5.1, <3"
